runtime: php55
version: 1
api_version: 1

handlers:
- url: /.*
  script: index.php

# [START env]
env_variables:
# Replace USER, PASSWORD, DATABASE, and CONNECTION_NAME with the
  # values obtained when configuring your Cloud SQL instance.
  # MYSQL_HOST: 35.186.178.70
  MYSQL_USER: backyardmedia 
  MYSQL_PASSWORD: backyardmedia2018
  # [END env]
